# Generated by Django 4.2.16 on 2024-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_tag_recipe_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredientAmount',
            new_name='RecipeIngredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
